[tool.poetry]
name = "tm-python-book"
version = "0.1.0"
description = ""
authors = ["TakiMoysha <mpwema782@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.23"
mypy = "^1.7.1"
flit = "^3.9.0"

[tool.poetry.group.robyn_http.dependencies]
robyn = "^0.46.0"
passlib = "^1.7.4"
jinja2 = "^3.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
